# Generated by Django 2.2.4 on 2019-10-02 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import downloads.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Author', downloads.models.NameField(max_length=500)),
                ('Author_original', models.CharField(max_length=500)),
                ('Title', models.CharField(max_length=500)),
                ('Publisher', models.CharField(max_length=500)),
                ('Year_published', models.CharField(max_length=500)),
                ('num_Pages', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=500)),
                ('Size', models.CharField(max_length=500)),
                ('Extension', models.CharField(max_length=500)),
                ('Mirrors', models.URLField(max_length=5000)),
                ('Edit', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBooks',
            fields=[
                ('ID', models.IntegerField(db_index=True)),
                ('Author', downloads.models.NameField(max_length=500)),
                ('Author_original', models.CharField(max_length=500)),
                ('Title', models.CharField(max_length=500)),
                ('Publisher', models.CharField(max_length=500)),
                ('Year_published', models.CharField(max_length=500)),
                ('num_Pages', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=500)),
                ('Size', models.CharField(max_length=500)),
                ('Extension', models.CharField(max_length=500)),
                ('Mirrors', models.URLField(max_length=5000)),
                ('Edit', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical books',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
