# Generated by Django 2.2.4 on 2019-08-21 23:56

from django.db import migrations, models
import json
from datetime import datetime

#datas = []
def json_load(apps,schema_editor):
    Books = apps.get_model('downloads','Books')
    
    def open_html(path):
        with open(path, 'r') as f:
            return json.load(f)

    data = open_html('downloads/static/downloads/book_dict')
    #datas = data
    #book_data = []
    for row in data:
    	l = Books.objects.get_or_create(
    		ID = row['ID'],
    		Author = row['Author(s)'],
    		Title = row['Title'],
			Publisher = row['Publisher'],
			Year_published = row['Year'],
			num_Pages = row['Pages'],
			Language = row['Language'],
			Size = row['Size'],
			Extension = row['Extension'],
			Mirrors = row['Mirrors'],
			Edit = row['Edit'],

    		)
        #book_data.append(row)

    #Books.objects.bulk_create(book_data)



class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(json_load),
    ]
