# Generated by Django 2.2.4 on 2019-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_auto_20190823_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Mirrors',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='Mirrors',
            field=models.URLField(max_length=5000),
        ),
    ]
